---
- hosts: tag_Name_DockerServer
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
# install packages to allow apt to use a repository over HTTPS:
  - name: Install docker packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present

# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

# apt-key fingerprint
  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present

# add-apt-repository
  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
      update_cache: yes

# apt-get update
  - name: Update apt packages
    apt:
      update_cache: yes

# install docker-ce latetst verion
  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes

  - name: Install prerequisites for docker-compose
    apt:
      name: ['python3-pip', 'python3-setuptools', 'virtualenv']
      update_cache: yes

  - name: Install docker-compose
    pip:
      name: docker-compose

# This is optional you may to add your user to docker group 

# sudo groupadd docker
  - name: Create "docker" group
    group:
      name: "docker"
      state: present

# sudo usermod -aG docker root
  - name: Add remote ubuntu user to docker group
    user:
      name: "ubuntu"
      group: "docker"
      append: yes
